version: '2.2'
services:
    # Postgres
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=tryit
            - POSTGRES_PASSWORD=out
            - POSTGRES_DB=app
        ports:
            - "5555:5432"
    # Flask
    app:
        build:
            context: ./app
        volumes:
            - ./app:/usr/local/app

        command: >
            /bin/bash -c "
                sleep 5
                python flask_migrations.py
                python app.py
                sleep infinity
            "
        environment:
            - SQLALCHEMY_DATABASE_URI=postgresql://tryit:out@postgres:5432/app
        depends_on:
            - postgres
        restart: always
        ports:
            - "5000:5000"




# Set up postgres.py
